version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    expose:
      - 8000

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - static_volume:/code/static
    ports:
      - "80:80"

volumes:
  postgres_data:
  static_volume: